"""empty message

Revision ID: 293521675738
Revises: 
Create Date: 2022-06-27 20:33:50.383017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293521675738'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dono',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('breed', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=True),
    sa.Column('raca', sa.String(length=20), nullable=True),
    sa.Column('dono', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dono'], ['dono.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donos_gatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dono', sa.Integer(), nullable=True),
    sa.Column('gato', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dono'], ['dono.id'], ),
    sa.ForeignKeyConstraint(['gato'], ['gato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donos_gatos')
    op.drop_table('cao')
    op.drop_table('gato')
    op.drop_table('dono')
    # ### end Alembic commands ###
