"""empty message

Revision ID: 70379de87499
Revises: 293521675738
Create Date: 2022-07-04 18:23:25.924655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70379de87499'
down_revision = '293521675738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cao', sa.Column('cor', sa.String(length=20), nullable=True))
    op.add_column('cao', sa.Column('data_nascimento', sa.Date(), nullable=True))
    op.add_column('cao', sa.Column('nacionalidade', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cao', 'nacionalidade')
    op.drop_column('cao', 'data_nascimento')
    op.drop_column('cao', 'cor')
    # ### end Alembic commands ###
